FROM alpine:3.15.4

ARG BUILD_DATE
ARG BUILD_REF

WORKDIR /service
ADD ./service /service

CMD ["./service"]

LABEL org.golang.image.created="${BUILD_DATE}" \
	  org.golang.image.title="effcient_go" \
	  org.golang.image.authors="ixugo <xx@golang.space>" \
	  org.golang.image.source="https://blog.golang.space" \
	  org.golang.image.revision="${BUILD_REF}" \
