apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: service-deploy
  name: service-deploy
  namespace: service-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: service
    spec:
      containers:
        - image: service-amd64:1.0
          name: service-amd64
          resources:
            limits:
              cpu: "2"
              memory: "1024Mi"
status: {}
