// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ixugo/efficient_go/demo/wire/core"
)

// Injectors from wire.go:

func InitApp() (*App, error) {
	config := core.NewConfig()
	db := core.NewDB(config)
	app := NewApp(db)
	return app, nil
}
