// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/ixugo/efficient_go/demo/orm/ent/schema"
	"github.com/ixugo/efficient_go/demo/orm/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescAge is the schema descriptor for age field.
	userDescAge := userFields[0].Descriptor()
	// user.DefaultAge holds the default value on creation for the age field.
	user.DefaultAge = userDescAge.Default.(int)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.DefaultName holds the default value on creation for the name field.
	user.DefaultName = userDescName.Default.(string)
	// userDescTree is the schema descriptor for tree field.
	userDescTree := userFields[2].Descriptor()
	// user.DefaultTree holds the default value on creation for the tree field.
	user.DefaultTree = userDescTree.Default.([]int)
}
